on:
push:
branches: [ "main" ]
workflow_dispatch:

jobs:
validation:
# Use the latest Ubuntu runner environment
runs-on: ubuntu-latest
jobs:
  test:
    steps:
      - name: 23f2003951@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      
